# Generated by Django 2.2.9 on 2020-02-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]
