# Generated by Django 3.0.3 on 2020-02-27 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_auto_20200224_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 27, 16, 12, 51, 307530, tzinfo=utc), verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='555-555-5555'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='employer_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='555-555-5555'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state_zip',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
