# Generated by Django 3.0.3 on 2020-03-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20200227_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
