# Generated by Django 3.0.3 on 2020-04-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_volunteer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(default='0001-01-01', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='emergency_contact_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='employer_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state_zip',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
